apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs               
spec:
  capacity:
    storage: 1Gi                                #指定请求存储空间的大小
  accessModes:
    - ReadWriteMany                             #一共有三种模式
  persistentVolumeReclaimPolicy: Recycle                #设置回收策略
  nfs:
    server: 192.168.31.250                               #指定nfs服务器地址
    path: "/home/test"                                   #指定nfs 服务器的共享目录
